elastic/elastic-otel-node

package-lock.json, package.json, packages/mockotlpserver/package.json, packages/opentelemetry-node/CHANGELOG.md, packages/opentelemetry-node/package.json
This is a follow-on from https://github.com/elastic/elastic-otel-node/pull/159
The release attempt failed to 'npm publish' in https://github.com/elastic/elastic-otel-node/actions/runs/8899712600/job/24439813707
```
npm WARN publish npm auto-corrected some errors in your package.json when publishing.  Please run "npm pkg fix" to address these errors.
npm WARN publish errors corrected:
npm WARN publish "repository.url" was normalized to "git+https://github.com/elastic/elastic-otel-java.git"
npm notice 
npm notice 📦  @elastic/opentelemetry-node@0.1.1
...
npm notice total files:   27                                      
npm notice 
npm notice Publishing to https://registry.npmjs.org/ with tag latest and public access
npm notice publish Signed provenance statement with source and build …
```
=> release 0.1.2; apply 'npm pkg fix' changes required by provenance generation

packages/mockotlpserver/lib/logs-summary.js
The normalized LogRecord, for better or worse, elides the 'attributes'
property if there are no attributes.
* * *
An example hitting this is with this:
```js
const pino = require('pino')
const transport = pino.transport({
target: 'pino-opentelemetry-transport'
})
const logger = pino(transport)
logger.info('hi');
```
The error before this fix was:
```
{"name":"mockotlpserver","level":50,"err":{"message":"Cannot convert undefined or null to object","name":"TypeError","stack":"TypeError: Cannot convert undefined or null to object\n    at Function.keys (<anonymous>)\n    at LogsSummaryPrinter.printLogs (/Users/trentm/el/elastic-otel-node/packages/mockotlpserver/lib/logs-summary.js:94:32)\n    at /Users/trentm/el/elastic-otel-node/packages/mockotlpserver/lib/printers.js:81:26\n    at …
```
=> fix(mockotlpserver): fix logs-summary crash on a LogRecord with no attributes

.github/dependabot.yml
This is a follow-up to #195 to attempt to get updates for
aws-sdk without all the noise.
=> chore: limit updates to aws-sdk-related packages to monthly

package-lock.json, scripts/update-otel-deps.js
Some resource detector improvements:
0.2.7 -> 0.2.9 @opentelemetry/resource-detector-azure
0.3.10 -> 0.3.11 @opentelemetry/resource-detector-container
0.28.9 -> 0.28.10 @opentelemetry/resource-detector-alibaba-cloud
0.29.9 -> 0.29.10 @opentelemetry/resource-detector-gcp
1.5.0 -> 1.5.1 @opentelemetry/resource-detector-aws
This also tweaks the update script to give some commands to run to create the PR, for convenience.
=> chore(deps): update deps matching "@opentelemetry/*"

.github/workflows/labeler.yml
Closes: #108
---
@elastic/observablt-robots Do you think the token I'm using here will work? Here is the relevant part of the "add-to-project" action README that discusses the token/PAT permissions required: https://github.com/actions/add-to-project?tab=readme-ov-file#creating-a-pat-and-adding-it-to-your-repository
=> chore: add new internal issues/PRs to GH project

.github/dependabot.yml
Refs: https://github.com/elastic/elastic-otel-node/pull/155
=> chore: skip eslint-related updates until we've upgraded to v9

packages/mockotlpserver/CHANGELOG.md, packages/mockotlpserver/lib/grpc.js, packages/mockotlpserver/lib/normalize.js, packages/mockotlpserver/package.json
Before this the gRPC server hadn't yet added the LogsService and MetricsService.
Fixes: #276
=> feat(mockotlpserver): handle logs and metrics via gRPC

packages/mockotlpserver/Dockerfile, packages/mockotlpserver/share/k8s/README.md, packages/mockotlpserver/share/k8s/create-kind-cluster-with-registry.sh, packages/mockotlpserver/share/k8s/example-app-manual/.npmrc, packages/mockotlpserver/share/k8s/example-app-manual/Dockerfile, packages/mockotlpserver/share/k8s/example-app-manual/app.js, packages/mockotlpserver/share/k8s/example-app-manual/deployment.yaml, packages/mockotlpserver/share/k8s/example-app-manual/package.json, packages/mockotlpserver/share/k8s/mockotlpserver-deployment.yaml, packages/mockotlpserver/share/k8s/mockotlpserver-service.yaml
This adds a Dockerfile that could be used later to publish image builds.
It also adds docs and Kubernetes deployment config to show how to
use mockotlpserver in k8s.
=> feat(mockotlpserver): Dockerfile and docs on using it in Kubernetes

package-lock.json, package.json
This reverts commit f865bc8ae0b4a640c42576f9ba9a47f02f7f2f64.
See some discussion at https://github.com/elastic/elastic-otel-node/pull/286#issuecomment-2232061859
The deps in question here are only *dev* deps, so it would *work* to require Node.js v20 for local dev. However, I'd prefer not to do that. Developing with Node.js v18 is reasonable (EOL is 2025-04-30, https://github.com/nodejs/release#release-schedule).
---
For comparison, see this discussion about pinning/updating these deps for apm-agent-nodejs.git:
https://github.com/elastic/apm-agent-nodejs/pull/4139
For that repo the `lru-cache` package is a *runtime* dep, so we have to be more picky.  Both that and this repo claim to support back to Node.js v14.17.
=> Revert "chore(deps-dev): bump glob from 10.4.3 to 11.0.0 (#286)"

.github/dependabot.yml
Today I noticed a new check failure on the latest commit to main. It was to
dependabot.yml. The failure:
> Your .github/dependabot.yml contained invalid details
> Update configs must have a unique combination of 'package-ecosystem', 'directory', and 'target-branch'. Ecosystem 'npm' has overlapping directories.
I don't know if this is a new constraint or was just not noticed before.
I am hoping dropping the 'monthly' block here will suffice. We will
just deal with aws-sdk updates weekly, distracting though that will be.
=> chore(dependabot): drop separate 'monthly' block for updating some npm deps

Makefile, packages/opentelemetry-node/test/docker-compose.yaml
First, add a Makefile for those with 'make' in their blood:
make all test
Also fix mssql image usage after breakage in the latest release, copying
what was done in https://github.com/elastic/apm-agent-nodejs/pull/4150
=> chore: add a convenience Makefile; fix mssql service in docker-compose

packages/opentelemetry-node/CHANGELOG.md, packages/opentelemetry-node/package-lock.json, packages/opentelemetry-node/package.json
Highlights:
- we added a number of instrumentations (still from the upstream auto-instrumentations-node set of instrs)
=> release @elastic/opentelemetry-node@0.3.0

package.json, scripts/oneach.sh
This is a convenience to run a command in each package dir.
Now that we are no longer using npm workspaces, we cannot
'npm run --workspaces ...'. This is mostly similar, except
it is a general command, not an npm script, that is run.
E.g.: npm run oneach -- npm ls @opentelemetry/sdk-node
=> chore: convenience 'npm run oneach -- CMD...'

packages/mockotlpserver/lib/printers.js
When playing with deep log records, e.g. with:
```js
logger.info('the message', {
aNum: 42,
aStr: 'str',
aUint8Array: new Uint8Array([4,5,6]),
aInt8Array: new Int8Array([-7,8,9]),
anObj: {
numField: 43,
strField: 'str',
uint8ArrayField: new Uint8Array([10,11,12]),
},
});
```
the current depth wasn't showing the full object structure.
=> fix(mockotlpserver): bump up the depth on 'inspect' printer to always see the full data structure

packages/mockotlpserver/lib/logs-summary.js, packages/mockotlpserver/lib/normalize.js
Two things:
1. There was a crash when an attribute with `doubleValue` was being rendered. That's the fix in normalize.js.
2. The "log-summary" printer's rendering of events (https://opentelemetry.io/docs/specs/otel/logs/event-sdk/#emit-event) which typically (always?) have a structured Body and have no `severityText` sucked. This improves that.
E.g.:
```
------ logs (2 records) ------
[2024-08-14T01:14:13.685000000Z] SEV-9 (instrumentation-openai-js-example):
hi from patchedCreate
asdf
if True:
print hi
--
foo: 'bar'
[2024-08-14T01:14:13.685000000Z] SEV-9 (instrumentation-openai-js-example): Event a-domain.a-event
{
field1: 'def',
field2: 42.42
}
--
'event.name': 'a-domain.a-event'
```
for these OTel JS calls:
```js
const logger = logs.getLogger(pj.name, pj.version);
logger.emit({ …
```
=> fix(mockotlpserver): support doubleValue attributes; improve rendering of log events where the body is typically an object, not a string

packages/mockotlpserver/CHANGELOG.md, packages/mockotlpserver/lib/normalize.js
The error was: 'TypeError: v.kvlistValue.values is not iterable'
=> fix(mockotlpserver): fix normalization of empty kvlistValue attributes

packages/mockotlpserver/lib/waterfall.js
E.g.:
span 99bb32 "chat llama3.1:latest" (7475.4ms, SPAN_KIND_CLIENT, GenAI openai, finish_reasons=tool_calls, tokens 209in/22out)
The part from "GenAI" on are the added extra attributes included.
This shows a subset of semconv v1.27 gen_ai attrs.
=> feat(mockotlpserver): show some GenAI-related span details in trace summary view

.github/dependabot.yml
The inclusion of the smithy pattern in the opentelemetry group
was a mistake.
=> chore(deps): tweak dependabot config

packages/mockotlpserver/CHANGELOG.md, packages/mockotlpserver/package-lock.json, packages/mockotlpserver/package.json
This sets publishConfig.access=public, required to publish a
scoped package -- scoped packages default to private.
=> release @elastic/mockotlpserver@0.4.1

packages/mockotlpserver/CHANGELOG.md, packages/mockotlpserver/lib/cli.js, packages/mockotlpserver/lib/mockotlpserver.js, packages/mockotlpserver/package-lock.json, packages/mockotlpserver/package.json, packages/opentelemetry-node/test/testutils.js
This fixes the CLI script so starting via npx works.
This also adds the '-l, --log-level LEVEL' CLI option.
Also add opts.logLevel to MockOtlpServer to simplify making it quiet for testing
=> release @elastic/mockotlpserver@0.5.0

.github/workflows/release.yml, DEVELOPMENT.md, examples/otel-operator/Dockerfile, examples/otel-operator/README.md, examples/otel-operator/app.js, examples/otel-operator/deployment.yaml, examples/otel-operator/instrumentation.yaml, examples/otel-operator/package.json, packages/opentelemetry-node/Dockerfile, packages/opentelemetry-node/autoinstrumentation.js, scripts/gen-notice.sh
This adds publishing of a docker.elastic.co/observability/elastic-otel-node
Docker image that can be used with the OpenTelemetry Operator to support
auto-instrumentation of Node.js apps in Kubernetes containers. The image
is a build of EDOT Node.js.
Refs: https://github.com/elastic/elastic-otel-node/issues/255
So far this is just the build/code changes required: no docs, tests, etc. Some of the following may be moved to a separate PR.
=> feat(opentelemetry-node): publish a Docker image to be used with the OTel Operator for k8s

examples/some-metrics.js, packages/mockotlpserver/CHANGELOG.md, packages/mockotlpserver/lib/metrics-summary.js
Also add an example to demonstrate using the various custom metrics
types.
=> fix(mockotlpserver): don't throw when printing a metrics summary for a histogram with no attributes

.github/dependabot.yml
Dependabot updates of the examples dir has been warning recently with:
updater | 2024/09/30 01:28:04 WARN <job_892539850> Please check your configuration as there are groups where no dependencies match:
- examples
This can happen if:
- the group's 'pattern' rules are misspelled
- your configuration's 'allow' rules do not permit any of the dependencies that match the group
- the dependencies that match the group rules have been removed from your project
=> chore: flail to attempt to fix dependabot updates for examples/ dir

.github/dependabot.yml
This time we'll remove the grouping to see if that helps.
We would *like* dependabot updates for examples/ to all be in a single group,
but that isn't working, so we'll take separate update PRs instead if that works.
Refs: #384 (flail attempt 1)
=> chore: flail (take 2) to attempt to fix dependabot updates for examples/ dir

examples/package.json
This time we'll remove the relative dep, on the theory that it is
tripping up dependabot. Keeping it this way puts a burden on the
developer that wants to test exapmles with local changes. Perhaps that
is fine for now. Arguably though this is the tail wagging the dog.
Refs: #384 (flail attempt 1)
Refs: #386 (flail attempt 2)
=> chore: flail (take 3) to attempt to fix dependabot updates for examples/ dir

.github/workflows/release-mockotlpserver.yml, .github/workflows/release.yml, Makefile, package.json, packages/opentelemetry-node/CHANGELOG.md, packages/opentelemetry-node/package-lock.json, packages/opentelemetry-node/package.json
The 0.4.0 release workflow failed to create the GitHub release entry (the last step):
https://github.com/elastic/elastic-otel-node/actions/runs/11149243541/job/30987681502
```
./scripts/github-release.sh: line 46: /home/runner/work/elastic-otel-node/elastic-otel-node/node_modules/.bin/json: No such file or directory
Error: Process completed with exit code 127.
```
This change fixes the release workflow and bumps to v0.4.1 for a new release.
(This also adds the `make clean` convenience and improves the ci-all and clean-all npm scripts.)
=> release @elastic/opentelemetry-node@0.4.1

packages/opentelemetry-node/CHANGELOG.md, packages/opentelemetry-node/package-lock.json, packages/opentelemetry-node/package.json
A regular release to include a few bumps of otel deps.
=> release @elastic/opentelemetry-node@0.5.0

packages/mockotlpserver/CHANGELOG.md, packages/mockotlpserver/lib/logs-summary.js, packages/mockotlpserver/lib/metrics-summary.js, packages/mockotlpserver/lib/styling.js, packages/mockotlpserver/lib/waterfall.js
- Show attributes for histogram metrics and handle showing multiple data points.
- Bold "span", "event", "$metricType" in renderings; and style the name of that
span/event/metric in magenta. See PR for screenshots.
--
Mainly this PR is about actually showing multiple metrics data points rather than a log warning.
The style changes are to try to make things pop a little bit to try to help find the separate pieces of data.
A couple screenshots showing what I mean.
=> feat(mockotlpserver): some improvements to "summary" styling

.github/workflows/release-instrumentation-openai.yml, packages/instrumentation-openai/CHANGELOG.md, packages/instrumentation-openai/package-lock.json, packages/instrumentation-openai/package.json
Fix the release workflow to install deps and compile before published,
otherwise a mostly empty package is published.
=> release instrumentation-openai 0.4.0

packages/instrumentation-openai/src/internal-types.ts
Some of the internal-types can use the api-logs AnyValue type.
=> chore(instrumentation-openai): use 'AnyValue' from api-logs rather than any

packages/instrumentation-openai/README.md
Make it so the user can just cut 'n paste and not have to work too
hard. The only real user effort here is adding their OpenAI key.
=> doc(instr-openai): improve the README first usage example

packages/mockotlpserver/package.json
This avoids accidentally publishing any db/trace-*.ndjson files that might
be kicking around in that directory from usage of the mock server.
=> fix(mockotlpserver): be explicit about what under db/ to include in published package

packages/mockotlpserver/CHANGELOG.md, packages/mockotlpserver/lib/http.js
Fixes: #477
---
Before this we were returning `{"ok": 1}` (i.e. JSON) as the response body to a http/protobuf request and I think recent changes in OTel JS's exporter was complaining about it. Responding with an empty body seems to suffice.
=> fix(mockotlpserver): return a valid response to http/protobuf requests

package.json, packages/mockotlpserver/lib/types-proto.d.ts, packages/mockotlpserver/opentelemetry/proto/collector/README.md, packages/mockotlpserver/opentelemetry/proto/metrics/v1/metrics.proto, packages/mockotlpserver/package.json, packages/mockotlpserver/scripts/update-protos.js
This also moves the script for updating the protos from the
top-level into the mockotlpserver package dir.
The v1.4.0 update was basically all profiles, so no update
effectively for us.
=> chore(mockotlpserver): update protos to v1.4.0

.github/workflows/release-mockotlpserver.yml, packages/mockotlpserver/CHANGELOG.md, packages/mockotlpserver/lib/http.js, packages/mockotlpserver/package-lock.json, packages/mockotlpserver/package.json, scripts/extract-release-notes.sh
This bumps mockotlpserver to v0.6.0 for release.
It also tweaks the notes added to GitHub releases from this
repo to include links to the package README and changelog.
It also adds build/push of a mockotlpserver Docker image
during release:
ghcr.io/elastic/elastic-otel-node/mockotlpserver
Closes: #467
=> release mockotlpserver 0.6.0

.github/workflows/release-mockotlpserver.yml, packages/mockotlpserver/CHANGELOG.md, packages/mockotlpserver/package-lock.json, packages/mockotlpserver/package.json
Fix Docker publishing. The handling for getting a Docker tag
from the git tag was broken because of the mockotlpserver-
prefix.
=> release mockotlpserver 0.6.1

packages/instrumentation-openai/CHANGELOG.md, packages/instrumentation-openai/package-lock.json, packages/instrumentation-openai/package.json, scripts/gen-notice.sh
A release with the LICENSE file included fixes an issue with
building the *EDOT* Docker image, because the in-'docker build'
run of scripts/gen-notice.sh no longer needs to dig into
'packages/instrumentation-openai/...' to find its license file
text.
---
Here is an example of the EDOT Node.js build failure while building its Docker image:
https://github.com/elastic/elastic-otel-node/actions/runs/12382883805
The issue is that it runs gen-notice.sh in the Docker build context,
but a recent workaround comment fixed `gen-notice.sh` to get
the instr-openai/LICENSE from the source tree. That fails in the
Docker build context. Either we copy that "packages/instrumentation-openai/LICENSE"
into the Docker build context, or we (a) get a new instr-openai release
with a license file, and (b) update …
=> release instrumentation-openai 0.4.1

.github/workflows/release-mockotlpserver.yml, packages/mockotlpserver/CHANGELOG.md, packages/mockotlpserver/package-lock.json, packages/mockotlpserver/package.json
Fix another couple issues with Docker build/push in CI.
This fixes a failure seen here: https://github.com/elastic/elastic-otel-node/actions/runs/12382422883
Also add the requisite token permission for pushing a package to ghcr.io.
=> fix Docker build in CI; release mockotlpserver 0.6.2

packages/opentelemetry-node/CHANGELOG.md, packages/opentelemetry-node/package-lock.json, packages/opentelemetry-node/package.json, scripts/gen-notice.sh
This adds an instrumentation for the 'openai' client
library: `@elastic/opentelemetry-instrumentation-openai`.
=> release @elastic/opentelemetry-node@0.6.0

packages/instrumentation-openai/src/instrumentation.ts, packages/instrumentation-openai/src/utils.ts
... because GH has a 'feature' called 'annotations' to show these warnings
on all PR diffs, even if that file was not part of that PR. There isn't
a way to turn this misfeature off in GH, so this is the tail wagging the dog
a bit.
Refs: https://github.com/elastic/elastic-otel-node/pull/480#issuecomment-2548777949
=> chore(instr-openai): avoid '@typescript-eslint/no-explicit-any' warnings

.github/workflows/slack.yml
The typical way to get notifications in Slack for various actions in a GitHub repo is via https://github.com/integrations/slack, the GitHub-maintained integration for Slack.
This integration has the following issues with its notifications for GitHub issue and PR actions:
- It is over-wordy, resulting in notification noise masking any other conversation in the channel. This lowers the signal-to-noise ratio in the channel, which discourages meaningful conversation.
- It includes some body content from issues/PRs. This may be a nice idea for a repo with commonly simple and short issue/PR descriptions. However, in practice (IMHO) it is rarely enough to avoid the need to visit the full issue in the browser to meaningfully understand and interact with the issue/PR. It can also get silly for PRs …
=> chore: Slack notifications for issue/PR open/close actions

.github/workflows/slack.yml
Refs: https://github.com/elastic/apm-agent-nodejs/pull/4401
=> chore: copy improved slack-lite notification styling from apm-agent-nodejs.git

packages/instrumentation-openai/README.md, packages/instrumentation-openai/examples/openai.js, packages/instrumentation-openai/test/fixtures.test.js
Some earlier similar renaming had already been done. This picks up some stragglers.
=> chore: s/MODEL_CHAT/CHAT_MODEL/ in example and test envvars for consistency and clarity

.github/workflows/labeler.yml, .github/workflows/lint.yml, .github/workflows/release-instrumentation-openai.yml, .github/workflows/release-mockotlpserver.yml, .github/workflows/release.yml, .github/workflows/slack.yml, .github/workflows/test-edot.yml, .github/workflows/test-instrumentation-openai.yml
This is (a) to avoid the GH Actions warnings in workflow runs, e.g.:
ubuntu-latest pipelines will use ubuntu-24.04 soon. For more details, see https://github.com/actions/runner-images/issues/10636
and (b) to try it out ahead of the switch.
=> chore(ci): change from ubuntu-latest to ubuntu-24.04

examples/openai/.editorconfig, examples/openai/.prettierrc, examples/openai/chat.js, examples/openai/embeddings.js
Use atypical (for this repo) 2-space indent to help avoid fighting
80-columns reflow, for use in a blog post where appearance matters
a little bit more.
=> chore(examples): tighten up the openai chat example a bit

.github/workflows/slack.yml
This fixes a 'SlackError: Missing input!' error when skipping a
notification, e.g. for a dependabot PR:
https://github.com/elastic/elastic-otel-node/actions/runs/12743214047/job/35512726091?pr=526
=> fix(slack notifications): don't attempt to post a slack message if don't have one

examples/package-lock.json, examples/package.json
This updates all deps in examples/, including an update to express
that includes dep updates for a couple low severity security issues.
---
Aside: I'm not entirely sure why dependabot didn't create some of these updates. It could be that it hit its weekly limit.
=> chore(examples): update deps

packages/instrumentation-openai/.npmrc
This is the default lockfileVersion used npm v9 and later. Node v18,
our min-supported Node.js version, includes npm v10.
Setting this config should ensure that dependabot updates don't
revert the lockfileVersion back to 2.
---
An example of that dependabot switching back to version 2 is here: https://github.com/elastic/elastic-otel-node/pull/543/files#diff-9d4a71f54ee443bf35be8c8af1bea61586971a4b0eca5d2d2be9262804de42e0R4
=> chore(instr-openai): lock package-lock file version to v3

.github/workflows/test-edot.yml, examples/package.json, packages/opentelemetry-node/CHANGELOG.md, packages/opentelemetry-node/docs/supported-technologies.md, packages/opentelemetry-node/package-lock.json, packages/opentelemetry-node/package.json, packages/opentelemetry-node/test/docker-compose.yaml, packages/opentelemetry-node/test/fixtures/use-elasticsearch.js, packages/opentelemetry-node/test/fixtures/use-elasticsearch.mjs, packages/opentelemetry-node/test/instr-elasticsearch.test.js, packages/opentelemetry-node/test/test-services.env
As of `@elastic/elasticsearch` 8.15.0, the ES client package has native
OTel instrumentation. This adds a test to sanity check that.
Closes: https://github.com/elastic/elastic-otel-node/issues/28
This is in draft until there is a 8.15.0 release to test with.
=> test: add a test for native @elastic/elasticsearch instrumentation

packages/mockotlpserver/CHANGELOG.md, packages/mockotlpserver/lib/waterfall.js
Before:
```
------ trace 43670f (3 spans) ------
span 7dc366 "Test Parent" (2007.4ms, SPAN_KIND_INTERNAL)
+1ms `- span f84ec1 "Test Child 1" (1003.2ms, SPAN_KIND_INTERNAL)
+1s `- span 534247 "Test Child 2" (1002.1ms, SPAN_KIND_INTERNAL)
```
After:
```
------ trace 43670f (3 spans) ------
span 7dc366 "Test Parent" (2007.4ms, SPAN_KIND_INTERNAL)
+1ms `- span f84ec1 "Test Child 1" (1003.2ms, SPAN_KIND_INTERNAL)
+1s  `- span 534247 "Test Child 2" (1002.1ms, SPAN_KIND_INTERNAL)
```
=> fix(mockotlpserver): fix an alignment issue in trace-summary gutter with 1-char units

.github/workflows/test-edot.yml, packages/opentelemetry-node/test/instr-elastic-openai.test.js
This temporarily disables the flaky instr-elastic-openai.test.js
until the Ollama crash bug https://github.com/ollama/ollama/issues/8400
is resolved.
As well, this improves the test file's handling for pulling the test
model. Before this the setup code was errorneously assuming the
Ollama response statusCode would indicate success. It doesn't.
Refs: https://github.com/elastic/elastic-otel-node/issues/587
=> test(edot): temporarily disable instr-elastic-openai.test.js

packages/opentelemetry-node/CHANGELOG.md, packages/opentelemetry-node/package-lock.json, packages/opentelemetry-node/package.json
Highlights:
- Bump min-supported node to `^18.19.0 || >=20.6.0`. This *drops support* for Node.js 14 and 16. (#584)
- Better ESM instrumentation bootstrapping. The recommendation for starting EDOT Node.js has changed from using `--require` to using `--import`. E.g.: `node --import @elastic/opentelemetry-node my-app.js`. (#584)
- Add instrumentations: mysql, mysql2, amqplib, cassandra-driver
=> release @elastic/opentelemetry-node@0.7.0

packages/opentelemetry-node/docs/supported-technologies.md, packages/opentelemetry-node/lib/instrumentations.js, packages/opentelemetry-node/test/instr-fastify.test.js
Adds `@opentelemetry/instrumentation-fastify` into the list of disabled instrumentations. It also places a new section in `supported-tchnologies.md` to let the user know which instrumentations are disabled and how to re-enable it.
Closes: #556
=> chore(otel-node): disable fastify instrumentation and update docs

packages/opentelemetry-node/CHANGELOG.md, packages/opentelemetry-node/lib/logging.js, packages/opentelemetry-node/lib/metrics/host.js, packages/opentelemetry-node/package-lock.json, packages/opentelemetry-node/package.json
Closes: https://github.com/elastic/elastic-otel-node/issues/606
Refs: https://github.com/open-telemetry/opentelemetry-js/issues/4832
=> chore(otel-node): use peerDeps for otel/api dep, cap it to a known-supported maximum

packages/opentelemetry-node/README.md
Refs: https://github.com/elastic/opentelemetry-dev/issues/722
=> docs(opentelemetry-node): document the differences with upstream OTel JS SDK

packages/mockotlpserver/lib/metrics-summary.js, packages/mockotlpserver/lib/waterfall.js
For example, when using this to compare (I'm setting `TEMPORALITY_PREFERENCE=delta` here because the PR to do that by default isn't in yet):
```
cd examples
OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE=delta node --import @elastic/opentelemetry-node simple-http-request.js
```
Pros:
- can meaningfully see this metric data in the "summary" output
Cons:
- Much taller output with the default metrics coming from EDOT Node.js... so things aren't as compact.
Still I think it is obviously better. If one doesn't care to look at metrics in mockotlpserver summary output, then one can:
```
npx mockotlpserver -o inspect,trace-summary,logs-summary   # i.e. exclude 'metrics-summary'
```
=> feat(mockotlpserver): summary rendering of Sum and Gauge metric types

examples/package-lock.json, examples/package.json
Before this change to examples were relying on 'npm run ci-all'
being run at the top-level, which is kinda lame. Now examples
should work via `cd examples && npm ci`.
Also add a 'npm run dev:use-local-edot-nodejs' for local dev
to use the local EDOT Node.js package.
=> fix(examples): get examples to work independently

packages/opentelemetry-node/lib/sdk.js, packages/opentelemetry-node/test/OTEL_EXPORTER_OTLP_PROTOCOL.test.js, packages/opentelemetry-node/test/OTEL_METRICS_EXPORTER.test.js
=> fix(otel-node): use sdk to resolve metrics exporters

packages/mockotlpserver/lib/http.js
OTEL agents which run in a web application may send data to a collector which is not in the same domain. In this scenario browsers do check CORS in order to do the actual request. The server now handle `OPTIONS` requests and sends back the required headers for CORS.
=> feat: add CORS support for browser agents

.github/CODEOWNERS, .github/dependabot.yml
https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/
> ... we’re removing the [Dependabot reviewers configuration option](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#reviewers--) on Tuesday, May 20, 2025.
=> chore: use CODEOWNERS instead of 'reviewers' in dependabot.yml

packages/opentelemetry-node/lib/sdk.js
The deprecation of `ELASTIC_OTEL_METRICS_DISABLED` [PR](https://github.com/elastic/elastic-otel-node/pull/768) changed a bit the behaviour of EDOT.  Although no metric is exported when setting it to `true` the nodejs runtime instrumentation is activated and previously it wasn't
After a discussion there is an agreement on restoring the same behaviour. Ref: https://github.com/elastic/opentelemetry/pull/230/files#r2093462817
It has been tested locally that the env var `OTEL_NODE_DISABLED_INSTRUMENTATIONS` is updated properly before resolving the instrumentation list.
=> chore: restore ELASTIC_OTEL_DISABLE_METRICS behaviour

packages/opamp-client-node/CHANGELOG.md, packages/opamp-client-node/package-lock.json, packages/opamp-client-node/package.json, packages/opamp-client-node/types/generated/anyvalue_pb.d.ts, packages/opamp-client-node/types/generated/opamp_pb.d.ts, packages/opamp-client-node/types/index.d.ts, packages/opamp-client-node/types/logging.d.ts, packages/opamp-client-node/types/opamp-client.d.ts, packages/opamp-client-node/types/utils.d.ts
Get `@elastic/opamp-client-node` to publish types, and make a v0.2.0 release.
=> release opamp-client-node 0.2.0; publish types

packages/opentelemetry-node/CHANGELOG.md, packages/opentelemetry-node/package-lock.json, packages/opentelemetry-node/package.json
- Restore support for bootstrapping via a custom file (e.g. `node --import ./telemetry.mjs ...`) rather than the typical `node --import @elastic/opentelemetry-node`.  This allows one to customize the SDK -- though we need to document this beyond the example at https://github.com/elastic/elastic-otel-node/blob/main/examples/telemetry.mjs.  Here is a TypeScript example: https://github.com/elastic/elastic-otel-node/blob/main/packages/opentelemetry-node/test/fixtures/an-esm-pkg/telemetry-typescript.ts
- Upstream `@opentelemetry/*` package updates including:
- `instrumentation-aws-sdk`: drop instrumentation for AWS SDK **v2**
- `instrumentation-express`: adds support for instrumenting express@5
=> release @elastic/opentelemetry-node@1.1.0

packages/opentelemetry-node/package.json
Installing and importing `@elastic/opentelemetry-node` in a project raises this error on startup:
```
npm install && npm run build && npm run start
node:internal/modules/run_main:104
triggerUncaughtException(
^
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/joshmock/Code/mcp-server-elasticsearch/node_modules/@elastic/opentelemetry-node/hook.mjs' imported from /home/joshmock/Code/mcp-server-elasticsearch/node_modules/@elastic/opentelemetry-node/import.mjs
at finalizeResolution (node:internal/modules/esm/resolve:275:11)
at moduleResolve (node:internal/modules/esm/resolve:860:10)
at defaultResolve (node:internal/modules/esm/resolve:984:11)
at nextResolve (node:internal/modules/esm/hooks:748:28)
at Hooks.resolve (node:internal/modules/esm/hooks:240:30)
at ModuleLoader.resolve …
```
=> Add missing file hook.mjs to published package

packages/opentelemetry-node/CHANGELOG.md, packages/opentelemetry-node/package-lock.json, packages/opentelemetry-node/package.json
v1.1.0 was a broken release because "hook.mjs" was not included in the published package (Fixed by https://github.com/elastic/elastic-otel-node/pull/835)
=> release @elastic/opentelemetry-node@1.1.1

scripts/gen-notice.sh, scripts/license.apache2.txt
The opentelemetry-node release process was failing in the docker
build after #740, because scripts/gen-notice.sh grew a dependency
on the top-level LICENSE file. This change breaks that dep, so
that the Dockerfile's usage of the ./scripts/ dir doesn't need
to worry about deps outside of that dir.
=> fix(opentelemetry-node): fix the Dockerfile build

packages/instrumentation-openai/CHANGELOG.md, packages/instrumentation-openai/package-lock.json, packages/instrumentation-openai/package.json
THis release is just to bump upstream otel deps, so that they align with the deps used by other instrumentations included in EDOT Node.js.
=> release @elastic/opentelemetry-instrumentation-openai 0.5.1

packages/mockopampserver/CHANGELOG.md, packages/mockopampserver/lib/mockopampserver.js, packages/mockopampserver/package-lock.json, packages/mockopampserver/package.json
Also expose 'MockOpAMPServer#setAgentConfigMap(...)' method for use in testing.
This is needed for https://github.com/elastic/elastic-otel-node/pull/886 testing.
=> release mockopampserver 0.4.0

packages/opentelemetry-node/test/testutils.js
The previous sorting of spans based on parentSpanId would fail if there
were *3 or more* spans with (a) the same start time millisecond and
(b) had parent/child relationships.
This case was happening frequently for me in local testing of instr-redis-4.test.js
=> test(opentelemetry-node): fix flaky instr-redis tests with fixed TestCollector.sortedSpans

docs/release-notes/breaking-changes.md, docs/release-notes/index.md, packages/opentelemetry-node/lib/instrumentations.js, packages/opentelemetry-node/package-lock.json, packages/opentelemetry-node/package.json, packages/opentelemetry-node/test/instr-redis.test.js, packages/opentelemetry-node/types/instrumentations.d.ts
Refs: https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2915
=> chore(opentelemetry-node): drop instr-redis-4, it is now consolidated into instr-redis

packages/mockotlpserver/CHANGELOG.md, packages/mockotlpserver/lib/grpc.js, packages/mockotlpserver/lib/http.js, packages/mockotlpserver/lib/mockotlpserver.js
This includes logging the headers/metadata which is useful for debugging
(e.g. knowing what user-agent is being sent).
=> feat(mockotlpserver): add a log.debug for incoming http and grpc requests

packages/mockotlpserver/CHANGELOG.md, packages/mockotlpserver/lib/cli.js, packages/mockotlpserver/lib/printers.js
So, for example, if I'm running mockotlpserver like this:
```
node lib/cli.js -o summary,spacer
```
and then run something that generates some telemetry like this (side note: the envvars I'm setting here are to reduce some of the noise from so many metrics being generated by default):
```
cd .../elastic-otel-node/examples
OTEL_NODE_DISABLED_INSTRUMENTATIONS=dns,net,runtime-node ELASTIC_OTEL_HOST_METRICS_DISABLED=true ELASTIC_OTEL_NODE_ENABLE_LOG_SENDING=true node --import @elastic/opentelemetry-node bunyan-logging-app.mjs
OTEL_NODE_DISABLED_INSTRUMENTATIONS=dns,net,runtime-node ELASTIC_OTEL_HOST_METRICS_DISABLED=true ELASTIC_OTEL_NODE_ENABLE_LOG_SENDING=true node --import @elastic/opentelemetry-node bunyan-logging-app.mjs
```
Now the mockotlpserver output will look like:
```
------ logs …
```
=> feat(mockotlpserver): 'spacer' printer to help view the output slightly

.github/dependabot.yml
Before this change we'd get separate dependabot updates for
EDOT Node.js and the directly otel deps. That results in large
churn in package-lock because those packages share so many
otel transitive deps.
Refs: https://github.com/elastic/elastic-otel-node/pull/1023
Refs: https://github.com/elastic/elastic-otel-node/pull/1022
=> chore: update deps in /examples all in one go

.github/dependabot.yml
Dependabot is configured per repo so we need your help to ensure that when “npm” is the package ecosystem that we set a cooldown to 14 days. See https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#cooldown-
=> Add cooldown period for npm dependency updates
